server:
  port: 8084
person:
  name: lisz
  age: 12
  gender: male
  likes:
    - books
    - movie
  last_name: Li
  email: lisz1012@gmail.com
#也可以在程序启动设置里面加一个VM Option： -Dspring.profiles.active=dev
spring:
  profiles:
    active: dev